ALTER TABLE users ADD COLUMN notify_ticket_created INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN notify_ticket_assigned INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN notify_ticket_done INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN notify_ticket_comment INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN notify_user_registered INTEGER NOT NULL DEFAULT 1;
